config/routes.rb
BodyTestWelcome::Application.routes.draw do
  devise_for :users, :controllers => {:confirmations => 'users/confirmations', registrations: 'users/registrations', passwords: 'users/passwords'}

  devise_scope :user do
    match "/confirm", to: 'users/confirmations#confirm', :as => :user_password_confirmation
  end

  resource :landing_flows, only: :show

  resource :personalizations, only: :new
  match "/save_user", to: 'personalizations#save_user', via: :put

  resource :personalization_surveys, only: [:edit, :update]
  resource :paywalls, only: :show

  root :to => 'landing_flows#show'
end

app/controllers/personalizations_controller.rb
#https://github.com/plataformatec/devise/wiki/How-To:-Email-only-sign-up

class PersonalizationsController < ApplicationController
  def new
    @user = current_user
    @personalization_survey = PersonalizationSurvey.new
    setup_survey_answers
  end

  def save_user
    get_personalization_responses
    @user = current_user
    @user.update_attributes(@user_params)
    @personalization_survey = PersonalizationSurvey.new(@p13n_referral)
    @personalization_survey.user = current_user

    if @user.save && @personalization_survey.save
      redirect_to edit_personalization_surveys_path
    else
      setup_survey_answers
      flash[:error] = "Please fix the following errors: A referral is required"
      render :new
    end
  end

  private

  def get_personalization_responses
    user_params = params.require(:user)
    personalization_survey = params.require(:personalization_survey)

    @user_params = user_params.permit(
      :first_name,
      :gender
    )

    @p13n_referral = personalization_survey.permit(:referral)
  end

  def setup_survey_answers
    @gender_hash = {
      'Male'   => 'm',
      'Female' => 'f'
    }
    @referral_hash = {
      'A friend'                             => 1,
      'Social Media (Facebook, Twitter, G+)' => 2,
      'Google'                               => 3,
      'News or Blog'                         => 4
    }
  end
end

app/helpers/personalizations_helper.rb
module PersonalizationsHelper
end

app/views/personalizations/_about_me_content.html.haml
#p13n-box.span6
  = form_for @user, url: save_user_path do |user|
    .p13n-survey-input-content
      .name
        .question What’s your first name?
        = user.text_field :first_name, :input_html => {:autofocus => true}
      .gender
        .question What's your gender?
        = user.select(:gender, options_for_select(@gender_hash), :include_blank => true)
        .p13n-dropdown-arrow-down
      = fields_for @personalization_survey, @user.personalization_survey do |survey|
        .referral
          .question How did you hear about us? *
          = survey.select(:referral, options_for_select(@referral_hash), :include_blank => true)
          .p13n-dropdown-arrow-down

    .p13n-submit-button
      = user.submit "Next, personalize your Body Test!"

app/views/personalizations/new.html.haml
- content_for(:subtitle) do
  %h1 Tell us about yourself

= render :partial => 'about_me_content'