config/routes.rb
BodyTestWelcome::Application.routes.draw do
  devise_for :users, :controllers => {:confirmations => 'users/confirmations', registrations: 'users/registrations', passwords: 'users/passwords'}

  devise_scope :user do
    match "/confirm", to: 'users/confirmations#confirm', :as => :user_password_confirmation
  end

  resource :landing_flows, only: :show

  resource :personalizations, only: :new
  match "/save_user", to: 'personalizations#save_user', via: :put

  resource :personalization_surveys, only: [:edit, :update]
  resource :paywalls, only: :show

  root :to => 'landing_flows#show'
end

app/controllers/landing_flows_controller.rb
class LandingFlowsController < ApplicationController
  before_filter :redirect_if_logged_in, only: :show

  def show
  end

  def redirect_if_logged_in
    if logged_in?
      if current_user.personalization_survey.nil?
        redirect_to new_personalizations_path
      else
        redirect_to_paywall
      end
    end
  end

  def redirect_to_paywall

    redirect_to PersonalizationSurveysController::BODY_TEST_PAYMENTS_URL
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/landing_flows_helper.rb
module LandingFlowsHelper
end

app/views/landing_flows/_signup_box.html.haml
#signup-box
  %h3 Learn more about the 8-week Body Test System
  #email-box
    = form_for resource, as: resource_name, url: registration_path(resource_name) do |form|
      = devise_error_messages!
      .input-form
        = form.email_field :email, :input_html => {:autofocus => true}, :placeholder => "What's your email address?"
        = form.submit "TAKE CONTROL"
  .subtext
    %p We're here to educate, not to spam you.

app/views/landing_flows/_top_section.html.haml
#landing-sub-headline
  .verb Learn how to use
  .left-bracket {
  .inside-bracket
    %ul
      %li food
      %li sleep
      %li mindfulness
      %li exercise
      %li habits
  .right-bracket }
  .verb to control your
  .left-bracket {
  .inside-bracket.decrease-side-margins
    %ul
      %li cravings
      %li hunger
      %li weight
      %li energy
      %li mood
  .right-bracket }

app/views/landing_flows/show.html.haml
- content_for(:subtitle) do
  %h1 No two bodies are the same. <br> Become an expert on yours.

- content_for(:topsection) do
  = render :partial => 'top_section'

= render :partial => 'signup_box'