config/routes.rb
BodyTestWelcome::Application.routes.draw do
  devise_for :users, :controllers => {:confirmations => 'users/confirmations', registrations: 'users/registrations', passwords: 'users/passwords'}

  devise_scope :user do
    match "/confirm", to: 'users/confirmations#confirm', :as => :user_password_confirmation
  end

  resource :landing_flows, only: :show

  resource :personalizations, only: :new
  match "/save_user", to: 'personalizations#save_user', via: :put

  resource :personalization_surveys, only: [:edit, :update]
  resource :paywalls, only: :show

  root :to => 'landing_flows#show'
end

app/models/personalization_survey.rb
class PersonalizationSurvey < ActiveRecord::Base
  belongs_to :user

  validates :user, :presence => true
  validates :referral, :presence => true

  attr_accessible :user_id, :referral, :goal, :understand_today, :obstacles,
                  :learn, :energy, :self_body_test, :water_consumed, :fatigue,
                  :vegetables_consumed, :exercise_per_week, :feel_hunger, :eat_junkfood
end

app/controllers/personalization_surveys_controller.rb
class PersonalizationSurveysController < ApplicationController
  BODY_TEST_PAYMENTS_URL = "http://www.thebodytest.com/pricing/"

  def edit
    @personalization_survey = current_user.personalization_survey
    setup_survey_answers
  end

  def update
    @personalization_survey = current_user.personalization_survey

    if @personalization_survey.update_attributes(survey_params)
      redirect_to BODY_TEST_PAYMENTS_URL
    else
      setup_survey_answers

      errors_array = @personalization_survey.errors.full_messages.map { |msg| msg }.join("\n")

      flash[:error] = "Please fix the following errors: \n #{errors_array}"

      render :edit
    end
  end

  private

  def survey_params
    survey_answers = params.require(:personalization_survey)
    survey_answers.permit(
      :goal,
      :understand_today,
      :obstacles,
      :learn,
      :energy,
      :self_body_test,
      :water_consumed,
      :fatigue,
      :vegetables_consumed,
      :exercise_per_week,
      :feel_hunger,
      :eat_junkfood
    )
  end

  def setup_survey_answers
    @goal_answers_hash = {
      'Lose weight'                        => 1,
      'Gain weight'                        => 2,
      'Feel healthier'                     => 3,
      'Feel more confident'                => 4,
      'Look more attractive'               => 5,
      'Look more attractive'               => 6,
      "Learn about my body's unique needs" => 7,
      'Live a healthier lifestyle'         => 8
    }

    @understand_today_answer_hash = {
      'Beginner: I don’t really know what I need to do to feel healthy' => 1,
      'Intermediate: I know a few behaviors that help me feel healthy'  => 2,
      'Advanced: I know a lot about how to feel healthy'                => 3
    }

    @obstacles_answer_hash = {
      "I’m too busy to cook"                  => 1,
      'I eat too much'                        => 2,
      'I drink too much'                      => 3,
      "I’m don’t exercise enough"             => 4,
      'I don’t sleep enough'                  => 5,
      'I’m too stressed'                      => 6,
      "I don’t know what to do"               => 7,
      'I need someone to hold me accountable' => 8
    }

    @learn_answer_hash = {
      'How much I should sleep'           => 1,
      'How much water I should drink'     => 2,
      'Which foods help me feel healthy'  => 3,
      'How to exercise'                   => 4,
      'How to form healthy habits'        => 5
    }

    @energy_answer_hash = {
      'I feel tired most of the day'      => 1,
      'I feel energetic part of the day'  => 2,
      'I feel energetic most of the day'  => 3
    }

    @self_body_test_hash = {
      'yes' => 1,
      'no'  => 2
    }

    @water_answer_hash = {
      '0-7 cups' => 1,
      '8 cups'   => 2
    }

    @fatigue_answer_hash = {
      'Very tired'                => 1,
      'A little tired'            => 2,
      'Energetic and well rested' => 3
    }

    @vegetables_answer_hash = {
      '0 Servings'   => 1,
      '1-4 Servings' => 2,
      '5+ Servings'  => 3
    }

    @exercise_answer_hash = {
      '0'      => 1,
      '1-2'    => 2,
      '3-4'    => 3,
      '5+'     => 4,
    }

    @hunger_answer_hash = {
      'Never'                           => 1,
      'Rarely (a few times a month)'    => 2,
      'Sometimes (a few times a week)'  => 3,
      'Often (several times a day)'     => 4,
      'Constantly (all day long)'       => 5
    }

    @junkfood_answer_hash = {
      'Never'                           => 1,
      'Rarely (a few times a month)'    => 2,
      'Sometimes (a few times a week)'  => 3,
      'Often (several times a day)'     => 4,
      'Constantly (all day long)'       => 5
    }
  end
end

app/helpers/personalization_surveys_helper.rb
module PersonalizationSurveysHelper
end

app/views/personalization_surveys/_survey_content.html.haml
#p13n-box-2.span6
  = form_for @personalization_survey, url: personalization_surveys_path(@personalization_survey) do |survey|
    .p13n-survey-input-content
      #p13n-survey-page-one
        #goal
          .question What do you hope to achieve from doing The Body Test?
          = survey.select(:goal, options_for_select(@goal_answers_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #understand
          .question How well do you think you understand your body today?
          = survey.select(:understand_today, options_for_select(@understand_today_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #obstacles
          .question What are the biggest obstacles that keep you from feeling your best?
          = survey.select(:obstacles, options_for_select(@obstacles_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        .learn
          .question What do you want to learn from your Body Test?
          = survey.select(:learn, options_for_select(@learn_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down

      #p13n-survey-page-two
        #energy
          .question How energetic are you?
          = survey.select(:energy, options_for_select(@energy_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #self-experiements
          .question Have you ever run self-experiments (or Body Tests) on yourself to better understand your body?
          = survey.select(:self_body_test, options_for_select(@self_body_test_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #water
          .question How much water do you drink each day?
          = survey.select(:water_consumed, options_for_select(@water_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #morning
          .question How do you feel when you wake up each morning?
          = survey.select(:fatigue, options_for_select(@fatigue_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #vegetables
          .question How many servings of vegetables do you eat each day?
          = survey.select(:vegetables_consumed, options_for_select(@vegetables_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #exercise
          .question How often do you exercise each week?
          = survey.select(:exercise_per_week, options_for_select(@exercise_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #hunger
          .question How often do you eat when you’re not physically hungry?
          = survey.select(:feel_hunger, options_for_select(@hunger_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down
        #junkfood
          .question How often do you eat processed food or junk food (chips, crackers, cookies, etc.)?
          = survey.select(:eat_junkfood, options_for_select(@junkfood_answer_hash), :include_blank => true)
          .p13n-dropdown-arrow-down

    .p13n-submit-button
      = survey.submit "TAKE THE NEXT STEP!"

app/views/personalization_surveys/edit.html.haml
- content_for(:subtitle) do
  %h1 Tell us about your healthy lifestyle goals
= render :partial => 'survey_content'